apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: docker-github-actions-runner
  namespace: webgrip
  title: GitHub Actions Runner - Docker
  description: |
    The GitHub Actions Runner service runs GitHub Actions in a Docker container.
  labels:
    tier: "2"
  annotations:
    github.com/project-slug: webgrip/docker-github-actions-runner
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=webhook-initializer'
  tags:
    - ci
    - automation
    - github
    - docker
    - runner
    - actions
  links:
    - url: https://github.com/webgrip/docker-github-actions-runner
      title: Source Code
      icon: github
      type: source
spec:
  type: service
  lifecycle: production
  owner: group:webgrip/infrastructure
  system: ci-system
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: ci-system
  namespace: webgrip
  title: CI/CD System
  description: |
    The CI system runs continuous integration pipelines.
  labels:
    tier: "2"
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - ci
    - automation
  links:
    - url: https://monitoring-platform.test
      title: Development URL
      icon: dashboard
      type: website
spec:
  owner: group:webgrip/infrastructure
  domain: webgrip/operations-domain
  type: infrastructure
