on:
  pull_request:

name: "Trigger: Push action"

jobs:
  tests:
    name: Tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
